version: "3.0"
#This file combines all the edge services and our services so that it can be deployed as a unit
services:
  predix-edge-postgres:
    image: "predix-edge-postgres-amd64:1.0.5"
    hostname: "predix-edge-postgres"
    ports:
      - 4334:4334
    networks:
      - predix-edge-broker_net
networks:
  predix-edge-broker_net:
    external: true
